### ISSUE TITLE
Make a release or revision compatible with pipes-4.3.*

### ISSUE THREAD

**Issue by DanBurton** [k0001/pipes-zlib#32]
The [latest pipes-zlib](https://hackage.haskell.org/package/pipes-zlib-0.4.4.1) is constrained to pipes < 4.3.

**Comment by bgamari** [comment]
A release would indeed be appreciated.

**Comment by k0001** [comment]
I created a new revision on Hackage removing this upper bound limit. There some loose ends in the development branch that I want to fix before making a new proper release. Thank you, and sorry for the delay.

**Comment by dimbleby** [comment]
But do you intend any *breaking* changes?

If not, can I please encourage you to consider releasing the current master branch sooner rather than later?  And then by all means make a subsequent minor release, at your leisure, to tidy up those loose ends.

(It's been quite a while now since you accepted my pull requests changing the handling of truncated and concatenated archives, and I'd love for that to hit hackage so that I can stop using my own private fork.)

**Comment by k0001** [comment]
@dimbleby there's an ongoing discussion here https://github.com/k0001/pipes-zlib/issues/29 -- I haven't been following this closely lately, I admit, but I recall I wasn't satisfied with how things ended up, and I don't want to push a new release until that's settled. I'll try and pick it up soon.

**Comment by dimbleby** [comment]
As best I remember that conversation, you'd like there to exist a function that operates on gzip archives, which decompresses all (concatenated) member archives, and which returns leftovers.

If that's right, I'll reiterate my plea: since this would be a new API I don't think that implementing it ought to block the release of all the *other* good stuff.  Don't make the perfect the enemy of the good!
