### ISSUE TITLE
Major version number in `master` should be bumped

### ISSUE THREAD

**Issue by bgamari** [k0001/pipes-zlib#35]
Currently the version number in `master` is 0.4.4.1, despite 0.4.4.2 being on Hackage and `master` containing breaking changes relative to the Hackage release.

**Comment by k0001** [comment]
You are right. Thank you. It looks like at some point in made the Hackage release from a different branch, and then those changes never went into `master`. 

Anyway, it's solved now. I included those missing changes and bumped the major version to `0.5`. 

Notice that I don't want to push this to Hackage until I revisit #29 and #30, since those are related to the changes that are in `master` already.
